from domains.domain import WEATHERS, SEASONS, COUNTRIES, CITIES, LOCATIONS, TIMES

WEATHER_INSTRUCTIONS = [f"Make it {x}" for x in WEATHERS]
SEASON_INSTRUCTIONS = [f"Make it {x}" for x in SEASONS]
COUNTRY_INSTRUCTIONS = [f"Make it {x}" for x in COUNTRIES]
CITY_INSTRUCTIONS = [f"Make it {x}" for x in CITIES]
LOCATION_INSTRUCTIONS = [f"Make it {x}" for x in LOCATIONS]
TIME_INSTRUCTIONS = [f"Make it {x}" for x in TIMES]

ALL_INSTRUCTIONS = [*WEATHER_INSTRUCTIONS, *SEASON_INSTRUCTIONS, *COUNTRY_INSTRUCTIONS, *CITY_INSTRUCTIONS, *LOCATION_INSTRUCTIONS, *LOCATION_INSTRUCTIONS]
